name: KovacsVoiceOver
favicon: null
layout_spectrum: 0.88632
typography_spectrum: 0.5164907139260322
title: Kovacs Voice Over
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#fefbea'
    - '#303030'
    - '#bfaa75'
    - '#997c44'
  brandStrength: 0.7449805659707636
  lightness: 0.16096071409992874
  saturation: 0.6875
  rhythmicContrast: 0.8935339171439409
purpose: []
