name: KovacsVoiceOver
favicon: null
layout_spectrum: 0.41325416159816086
typography_spectrum: 0.5164907139260322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7449805659707636
  lightness: 0.16096071409992874
  saturation: 0.2417290706653148
  rhythmicContrast: 0.8935339171439409
purpose: []
